[package]
name = "stacks"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
hex = { workspace = true }
k256 = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
